### ISSUE TITLE
Develop NoFMemberPicker

### ISSUE THREAD

**Issue by giovannifs** [fogbow/fogbow-manager#170]
As per title.

**Comment by abmargb** [comment]
- [ ] Implement NoFMemberPlugin
- [ ] Create PrioritizationPlugin
- [ ] implement NoF, TwoFold and No Prioritization plugin
- [ ] Create a queue for incoming requests
- [ ] Implement instance preemption (w/ instance deletion)

**Comment by abmargb** [comment]
Make use of a same-thread-executor for testing purposes. Test all features mentioned above in the integration environment.
