### ISSUE TITLE
Evaluate the average scheduling time given the current implementation of the ManagerController.checkAndSubmitOpenRequests() method

### ISSUE THREAD

**Issue by abmargb** [fogbow/fogbow-manager#202]
Currently, this method consumes the request queue using a single thread. We need to assess the average scheduling time given different amounts of requests being issued simultaneously. Such assessment will enlighten a discussion on using a request pool consumed by multiple threads versus the current implementation.

**Comment by fgan1** [comment]
Data found in the execution of the method.

Scenery 1: Manager A running and it is being created instances in the federation local quota (8 quota).

Observation : 
Request fulfilled: ~ 1 second for each request .
Request not fulfilled: ~ 600 milliseconds for each request.

- 10 Requests 
Time:  ~ 9 Second

- 50 Requests 
Time:  ~ 34 Second

- 250 Requests 
Time:  ~ 166 Second 

- 500 Requests 
Time:  ~ 276 Second

Cenário 2: Manager A and Manager B running and it is being created instances in the federation local quota (8 quota).

Observation :
Request fulfilled: ~ 1 second for each request.
Request not fulfilled: ~ 680 milliseconds for each request.

- 250 Requests 
Time:  ~ 204 Second

- 500 Requests 
Time:  ~ 385 Second

**Comment by giovannifs** [comment]
We implement batch-request (once one request from a batch requests fails, all other requests are not submitted on that time) and avoid unnecessary communication with underlying cloud (e.g. when local token is not informed).
