### ISSUE TITLE
Investigate volumes as federated resources

### ISSUE THREAD

**Issue by abmargb** [fogbow/fogbow-manager#208]
Currently we only federate instances (created by implementations of the ComputePlugin, issued by instance requests) and images (indirectly created by implementations of the ImageStoragePlugin). Investigate how volumes could be created and managed at the FM level.

**Comment by giovannifs** [comment]
We could create a **StoragePlugin** and provide the endpoint **/storage** at FM. The volume created in a specific federation member must be attached only in instances created there (by same user) as well. According to OCCI's sintaxe, FM must provide the endpoint **/storage/link/** to allow attach volumes to compute instances.

Follows some examples of volume's operations (we get these examples from here):

* Create a volume (initially FM could provide creation of volume only through order)
```
curl -v -X POST localhost:8787/storage/ -H 'Category: storage; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"' -H 'Content-Type: text/occi' -H 'X-Auth-Token: '$KID -H 'X-OCCI-Attribute: occi.storage.size = 1.0'
```
* Show the volume details:
```
curl -v -X GET localhost:8787/storage/$VOL -H 'Content-Type: text/occi' -H 'X-Auth-Token: '$KID
```
* Delete the volume:
```
curl -v -X DELETE localhost:8787/storage/$VOL -H 'X-Auth-Token: '$KID -H 'Content-Type: text/occi'
```
* Link and associate a volume to a compute instance:
```
curl -v -X POST localhost:8787/storage/link/ -H 'X-Auth-Token: '$KID -H 'Category: storagelink; scheme="http://schemas.ogf.org/occi/infrastructure#"; class="kind"' -H 'X-OCCI-Attribute: occi.core.source="http://localhost:8787/compute/'$VM'"' -H 'X-OCCI-Attribute: occi.core.target="http://localhost:8787/storage/'$VOL'"' -H 'X-OCCI-Attribute: occi.storagelink.deviceid="/dev/vdc"' -H 'Content-Type: text/occi'
```
* Inspect the storage link:
```
curl -v -X GET localhost:8787/storage/link/$VOL_LINK -H 'Content-Type: text/occi' -H 'X-Auth-Token: '$KID
```

A bit about implementation details, maybe it would be interesting to create a **ResourcePlugin** interface gathering the **requestInstance, getInstance and deleteInstance** methods, then **ComputePlugin** and **StoragePlugin** would extend this new plugin.
