### ISSUE TITLE
Green Sitter: Investigate integration with Open Nebula

### ISSUE THREAD

**Issue by RibeiroAna** [fogbow/fogbow-manager#209]
Investigate which message is reported by Open Nebula when no hosts are valid for the current request, so that the FM is able to properly invoke the Green Sitter.

**Comment by giovannifs** [comment]
Hi @RibeiroAna ,

How is being the working in this issue?

**Comment by RibeiroAna** [comment]
It is partially finished, we still must test it with a real deployment, so we can totally say that our greensiter is integrated with opennebula. :)
